name: Install shared software dependencies

inputs:
    os:
        description: "The current operating system"
        required: true
        type: string

runs:
    using: "composite"
    steps:

        - name: Setup Docker on Windows
          if: ${{ inputs.os == 'windows' }}
          shell: pwsh
          run: |
              Enable-WindowsOptionalFeature -Online -FeatureName containers -All
              choco install docker-desktop -y --params="'/LinuxContainers'"

        - name: Setup Docker on Mac
          if: ${{ inputs.os == 'macos' }}
          shell: bash
          run: |
              brew install docker colima qemu
              colima start --vm-type=qemu
              docker version
